# Generated by Django 3.1.7 on 2021-03-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('execution', models.CharField(max_length=100, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('finishedat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('age', models.CharField(max_length=255, null=True)),
                ('height', models.CharField(max_length=255, null=True)),
                ('average_earning', models.CharField(max_length=255, null=True)),
                ('clothes_expenses', models.CharField(max_length=255, null=True)),
                ('makeup_expenses', models.CharField(max_length=255, null=True)),
                ('creams_expenses', models.CharField(max_length=255, null=True)),
                ('adress', models.CharField(max_length=255, null=True)),
                ('note', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'firstone_person',
            },
        ),
    ]
