# Generated by Django 3.1.7 on 2021-03-29 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstOne', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='adress',
        ),
    ]
